/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.itson.presentacion.medios;

import com.itson.dominio.Etapa;
import com.itson.dominio.Medio;
import com.itson.dominio.Mesociclo;
import java.awt.GridLayout;
import java.awt.Label;
import java.awt.TextField;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author Andrea
 */
public class FrmPorcentajesMesociclos extends javax.swing.JFrame {

    private List<Etapa> etapas;
    private List<TextField> porcentajes;
    private List<Medio> medios;
    /**
     * Creates new form FrmPorcentajesMesociclos
     */
    public FrmPorcentajesMesociclos(List<Medio> medios) {
        initComponents();
        this.medios=medios;
        llenarComboboxMedios();
        generarTextField();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ScrollPanel = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        cmbMedios = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(5, 109, 182));
        jLabel5.setText("Porcentajes de volumen");

        jButton1.setText("Aceptar");

        jLabel1.setText("Medio:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(56, 56, 56))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbMedios, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbMedios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void llenarComboboxMedios(){
        for(Medio medio:medios){
            cmbMedios.addItem(medio.getMedio());
        }
    }
    /**
     * Crea los tectbox dependiendo de la cantidad de mesociclos
     */
    public void generarTextField(){
        int c=1;
        etapas=medios.get(0).getEtapas();
        
        Label lblTitulo1 = new Label("Etapa general");
        ScrollPanel.add(lblTitulo1);
        
        List<Mesociclo> mesosGeneral = etapas.get(0).getMesociclos();
        for(Mesociclo meso:mesosGeneral){
            JPanel jpanel = new JPanel(new GridLayout(mesosGeneral.size(), 1));
            
            Label lbl = new Label(String.valueOf(c));
            TextField txtMeso = new TextField();
            porcentajes.add(txtMeso);
            jpanel.add(lbl);
            jpanel.add(txtMeso);
            ScrollPanel.add(jpanel);
            c++;
        }
        
        Label lblTitulo2 = new Label("Etapa epecial");
        ScrollPanel.add(lblTitulo2);
        
        List<Mesociclo> mesosEspecial = etapas.get(1).getMesociclos();
        for(Mesociclo meso:mesosEspecial){
            JPanel jpanel = new JPanel(new GridLayout(mesosEspecial.size(), 1));
            
            Label lbl = new Label(String.valueOf(c));
            TextField txtMeso = new TextField();
            porcentajes.add(txtMeso);
            jpanel.add(lbl);
            jpanel.add(txtMeso);
            ScrollPanel.add(jpanel);
            c++;
        }
        
        Label lblTitulo3 = new Label("Etapa competitiva");
        ScrollPanel.add(lblTitulo3);
        
        List<Mesociclo> mesosCompetitiva = etapas.get(2).getMesociclos();
        for(Mesociclo meso:mesosCompetitiva){
            JPanel jpanel = new JPanel(new GridLayout(mesosCompetitiva.size(), 1));
            
            Label lbl = new Label(String.valueOf(c));
            TextField txtMeso = new TextField();
            porcentajes.add(txtMeso);
            jpanel.add(lbl);
            jpanel.add(txtMeso);
            ScrollPanel.add(jpanel);
            c++;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPanel;
    private javax.swing.JComboBox<String> cmbMedios;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
