// Copyright (c) Andrea Salazar Abigail Cárdenas, Alec Demian Santana Celaya, 
// Carlos Ariel Angulo Campos, Josue Emamnuel Flores Carballo, 
// Jesus Alejandro Izaguirre Gil. Licensed under the MIT Licence.
// See the LICENSE file in the repository root for full license text.
package com.itson.presentacion.nuevoRegimen;

import com.itson.dominio.Etapa;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComponent;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;

public class DefinirEtapas extends javax.swing.JFrame {

    /**
     * Creates new form DefinirEtapas
     */
    private List<Etapa> etapas = new ArrayList<>();
    private Long semanasTotal;
    
    public DefinirEtapas() {
        initComponents();

        JComponent general = GeneralSpinner.getEditor();
        if (general instanceof JSpinner.DefaultEditor) {
            JFormattedTextField textField = ((JSpinner.DefaultEditor) general).getTextField();
            textField.setEditable(false);
        }

        JComponent especial = EspecialSpinner.getEditor();
        if (especial instanceof JSpinner.DefaultEditor) {
            JFormattedTextField textField = ((JSpinner.DefaultEditor) especial).getTextField();
            textField.setEditable(false);
        }

        JComponent competitiva = CompetitivaSpinner.getEditor();
        if (competitiva instanceof JSpinner.DefaultEditor) {
            JFormattedTextField textField = ((JSpinner.DefaultEditor) competitiva).getTextField();
            textField.setEditable(false);
        }

    }
    
    public DefinirEtapas(Long totalSemanas) {
        initComponents();
        JComponent general = GeneralSpinner.getEditor();
        if (general instanceof JSpinner.DefaultEditor) {
            JFormattedTextField textField = ((JSpinner.DefaultEditor) general).getTextField();
            textField.setEditable(false);
        }

        JComponent especial = EspecialSpinner.getEditor();
        if (especial instanceof JSpinner.DefaultEditor) {
            JFormattedTextField textField = ((JSpinner.DefaultEditor) especial).getTextField();
            textField.setEditable(false);
        }

        JComponent competitiva = CompetitivaSpinner.getEditor();
        if (competitiva instanceof JSpinner.DefaultEditor) {
            JFormattedTextField textField = ((JSpinner.DefaultEditor) competitiva).getTextField();
            textField.setEditable(false);
        }
        this.semanasTotal=totalSemanas;
        
        totalSemanas=totalSemanas-6;
        TxtSemanasFaltantes.setText(totalSemanas.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CrearButton = new javax.swing.JButton();
        GeneralSpinner = new javax.swing.JSpinner();
        EspecialSpinner = new javax.swing.JSpinner();
        CompetitivaSpinner = new javax.swing.JSpinner();
        TxtSemanasFaltantes = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Definir Etapas");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(5, 109, 182));
        jLabel1.setText("Definir etapas");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(5, 109, 182));
        jLabel2.setText("General:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(5, 109, 182));
        jLabel3.setText("Especial:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(5, 109, 182));
        jLabel4.setText("Competitiva:");

        CrearButton.setBackground(new java.awt.Color(5, 109, 182));
        CrearButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CrearButton.setForeground(new java.awt.Color(255, 255, 255));
        CrearButton.setText("Crear");
        CrearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearButtonActionPerformed(evt);
            }
        });

        GeneralSpinner.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        GeneralSpinner.setModel(new javax.swing.SpinnerNumberModel(2, 2, 52, 1));
        GeneralSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                GeneralSpinnerStateChanged(evt);
            }
        });
        GeneralSpinner.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                GeneralSpinnerKeyTyped(evt);
            }
        });

        EspecialSpinner.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EspecialSpinner.setModel(new javax.swing.SpinnerNumberModel(2, 2, 52, 1));
        EspecialSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                EspecialSpinnerStateChanged(evt);
            }
        });

        CompetitivaSpinner.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CompetitivaSpinner.setModel(new javax.swing.SpinnerNumberModel(2, 2, 52, 1));
        CompetitivaSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                CompetitivaSpinnerStateChanged(evt);
            }
        });

        TxtSemanasFaltantes.setEditable(false);
        TxtSemanasFaltantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSemanasFaltantesActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(5, 109, 182));
        jLabel5.setText("Semanas faltantes:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CompetitivaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EspecialSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GeneralSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(TxtSemanasFaltantes, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(189, 189, 189))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(CrearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(239, 239, 239))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(GeneralSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtSemanasFaltantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(EspecialSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CompetitivaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(CrearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CrearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearButtonActionPerformed
        Etapa general = new Etapa("General", (int) GeneralSpinner.getValue());
        Etapa especial = new Etapa("Especial", (int) EspecialSpinner.getValue());
        Etapa competitiva = new Etapa("Competitiva", (int) CompetitivaSpinner.getValue());
        int validacionTotal=general.getTotalSemanas()+especial.getTotalSemanas()+competitiva.getTotalSemanas();
        if(semanasTotal!=validacionTotal){
            JOptionPane.showMessageDialog(this, "La cantidad de semanas no coincide con el total de semanas del regimen, intentelo de nuevo", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        etapas.add(general);
        etapas.add(especial);
        etapas.add(competitiva);
        DefinirMesociclo mesociclosFrame = new DefinirMesociclo(etapas);
        mesociclosFrame.setVisible(true);
        FrmCrearNuevoRegimen.setEtapasRegimen(etapas);
        super.dispose();
    }//GEN-LAST:event_CrearButtonActionPerformed

    private void GeneralSpinnerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GeneralSpinnerKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_GeneralSpinnerKeyTyped

    private void GeneralSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_GeneralSpinnerStateChanged
        int suma=(int)GeneralSpinner.getValue()+(int)CompetitivaSpinner.getValue()+(int)EspecialSpinner.getValue();
        TxtSemanasFaltantes.setText(String.valueOf(semanasTotal-suma));
    }//GEN-LAST:event_GeneralSpinnerStateChanged

    private void TxtSemanasFaltantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSemanasFaltantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtSemanasFaltantesActionPerformed

    private void EspecialSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_EspecialSpinnerStateChanged
        int suma=(int)GeneralSpinner.getValue()+(int)CompetitivaSpinner.getValue()+(int)EspecialSpinner.getValue();
        TxtSemanasFaltantes.setText(String.valueOf(semanasTotal-suma));
    }//GEN-LAST:event_EspecialSpinnerStateChanged

    private void CompetitivaSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_CompetitivaSpinnerStateChanged
        int suma=(int)GeneralSpinner.getValue()+(int)CompetitivaSpinner.getValue()+(int)EspecialSpinner.getValue();
        TxtSemanasFaltantes.setText(String.valueOf(semanasTotal-suma));
    }//GEN-LAST:event_CompetitivaSpinnerStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DefinirEtapas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DefinirEtapas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DefinirEtapas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DefinirEtapas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DefinirEtapas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner CompetitivaSpinner;
    private javax.swing.JButton CrearButton;
    private javax.swing.JSpinner EspecialSpinner;
    private javax.swing.JSpinner GeneralSpinner;
    private javax.swing.JTextField TxtSemanasFaltantes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
