// Copyright (c) Andrea Salazar Abigail Cárdenas, Alec Demian Santana Celaya, 
// Carlos Ariel Angulo Campos, Josue Emamnuel Flores Carballo, 
// Jesus Alejandro Izaguirre Gil. Licensed under the MIT Licence.
// See the LICENSE file in the repository root for full license text.
package com.itson.presentacion.nuevoRegimen;

import javax.swing.table.DefaultTableModel;
import java.nio.file.Files;
import java.nio.file.Paths;
import javax.swing.table.DefaultTableModel;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.itson.dominio.Etapa;
import com.itson.dominio.Medio;
import com.itson.dominio.Mesociclo;
import com.itson.dominio.Regimen;
import implementaciones.Persistencia;
import interfaces.IPersistencia;
import java.io.FileReader;
import java.util.List;

public class VistaPorMesociclo extends javax.swing.JPanel {

    private DefaultTableModel tableModel;
    private double totalVolumen;
    private int filas = 1;
    boolean columnasAgregadas = false;
    private Regimen regimen;
    
    public VistaPorMesociclo() {
        initComponents();
        tableModel = (DefaultTableModel) tbtMesociclos.getModel();
        
    }

    public void llenarTablaDesdeJSON(IPersistencia persistencia) {
        tableModel.setRowCount(0);
        
        try {
            regimen= persistencia.consultarRegimen();
            List<Medio> medios = regimen.getMedios();

            for (Medio medio : medios) {
                String nombreMedio = medio.getMedio();
                String primer = nombreMedio+ "(" + medio.getMedicion() + ")";

                // Calcular el totalVolumen específico para cada "medio"
                double totalVolumen = calcularTotalVolumen(medio);
                Object[] rowDataMedios = {primer, totalVolumen};
                tableModel.addRow(rowDataMedios);
            }
            List<Etapa> etapas = regimen.getEtapas();
                for (Etapa etapa : etapas) {
                    List<Mesociclo> mesociclos = etapa.getMesociclos();
                    for (Mesociclo mesociclo : mesociclos) {
                    llenarPorcentajesVol(mesociclo);
                }
            }
            columnasAgregadas = true;
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private double calcularTotalVolumen(Medio medio) {
        double totalVolumen = 0.0;

        List<Etapa> etapas = medio.getEtapas();

        for (Etapa etapa : etapas) {

            double volumenEtapa = etapa.getVolumen();
            totalVolumen += volumenEtapa;
        }

        return totalVolumen;
    }
   
    private boolean llenarPorcentajesVol(Mesociclo mesociclo) {
        int numRows = tableModel.getRowCount();

        int noMesociclo = mesociclo.getNoMesociclo();
        if (columnasAgregadas == false) {
            tableModel.addColumn("Mesociclo ");
            tableModel.addColumn("Vol");
            tableModel.addColumn("%");
        }
        for (int i = 0; i < numRows; i++) {
            tableModel.setValueAt(noMesociclo, i, tableModel.getColumnCount() - 3);
            tableModel.setValueAt(0, i, tableModel.getColumnCount() - 2);
            tableModel.setValueAt(0, i, tableModel.getColumnCount() - 1);
        }
        return columnasAgregadas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbtMesociclos = new javax.swing.JTable();

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(5, 109, 182));
        jLabel5.setText("Vista por mesociclo");

        tbtMesociclos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Medios físicos", "Volumen Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbtMesociclos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tbtMesociclos.setEnabled(false);
        tbtMesociclos.setGridColor(new java.awt.Color(255, 255, 255));
        tbtMesociclos.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tbtMesociclos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbtMesociclos;
    // End of variables declaration//GEN-END:variables
}
